baseURL = "https://jazellemaira.com"
title = "Jazelle Maira"
author = "Jazelle Maira"
copyright = "Jazelle Maira; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper3"

[params]
  facebook = "https://facebook.com/jazellemaira"
  twitter = "https://twitter.com/jazellemaira"
  instagram = "https://www.instagram.com/jazellemaira/"
  github = "https://github.com/jazellemaira"
  description = ""
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  # [[menu.main]]
  #   identifier = "image-credit"
  #   name = "Image Credit"
  #   url = "/image-credit/"
  #   weight = 20
  # [[menu.main]]
  #   identifier = "github-repo-theme"
  #   name = "Get Theme on Github"
  #   url = "https://github.com/jonathanjanssens/hugo-casper3"
  #   weight = 30
  [[menu.main]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/jazellemaira/"
    weight = 40

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
